CREATE TABLE core."GameServerVolumes"
(
	"Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"GameServerId" integer NOT NULL,
	"Usage" varchar(100) NOT NULL,
	"ContainerPath" varchar(500) NOT NULL,
	"Source" varchar(500) NOT NULL,
	"MountType" varchar(50) NOT NULL DEFAULT 'volume',
	"ReadOnly" boolean NOT NULL DEFAULT FALSE,
	"Driver" varchar(200) NOT NULL DEFAULT 'local',
	"DriverOptionsJson" jsonb NULL,
	"OwnerUid" integer NULL,
	"OwnerGid" integer NULL,
	"Permissions" varchar(10) NULL,
	"InitMode" varchar(50) NOT NULL DEFAULT 'none',
	"SeedSourcePath" varchar(500) NULL,
	"IsProvisioned" boolean NOT NULL DEFAULT FALSE,
	"CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
	CONSTRAINT "FK_GameServerVolumes_GameServers_GameServerId"
		FOREIGN KEY ("GameServerId") REFERENCES core."GameServers" ("Id") ON DELETE CASCADE,
	CONSTRAINT "UQ_GameServerVolumes_GameServerId_ContainerPath"
		UNIQUE ("GameServerId", "ContainerPath")
);

CREATE INDEX "IX_GameServerVolumes_GameServerId" ON core."GameServerVolumes" ("GameServerId");
