CREATE TABLE core."GameServerResourceUtilizations"
(
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ServerId" varchar(100) NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "CpuUsagePercent" double precision NULL,
    "MemoryUsageBytes" bigint NULL,
    "MemoryLimitBytes" bigint NULL,
    "MemoryUsagePercent" double precision NULL,
    "NetworkRxBytes" bigint NULL,
    "NetworkTxBytes" bigint NULL,
    "BlockReadBytes" bigint NULL,
    "BlockWriteBytes" bigint NULL,
    "DesiredReplicas" integer NOT NULL DEFAULT 0,
    "RunningReplicas" integer NOT NULL DEFAULT 0,
    "ContainerId" varchar(100) NULL
);

CREATE INDEX "IX_GameServerResourceUtilizations_ServerId" ON core."GameServerResourceUtilizations" ("ServerId");
CREATE INDEX "IX_GameServerResourceUtilizations_ServerId_Timestamp" ON core."GameServerResourceUtilizations" ("ServerId", "Timestamp");
