// <auto-generated />
using System;
using GameServer.Docker.Data.V2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameServer.Docker.Data.V2.Migrations.SqliteMigrations
{
    [DbContext(typeof(SqliteGameServerV2DbContext))]
    partial class SqliteGameServerV2DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("GameServer.Docker.Data.V2.GameServerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameTypeRevisionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastDeployedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("GameTypeRevisionId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ServerId")
                        .IsUnique();

                    b.ToTable("GameServers", (string)null);
                });

            modelBuilder.Entity("GameServer.Docker.Data.V2.GameServerSettingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameServerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameServerId", "SettingKey")
                        .IsUnique();

                    b.ToTable("GameServerSettings", (string)null);
                });

            modelBuilder.Entity("GameServer.Docker.Data.V2.GameServerVolumeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContainerPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Driver")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverOptionsJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnsureNfsPathExists")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameServerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsProvisioned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MountType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OwnerGid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OwnerUid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Permissions")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ReadOnly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Usage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("VolumeName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameServerId");

                    b.HasIndex("GameServerId", "ContainerPath")
                        .IsUnique();

                    b.ToTable("GameServerVolumes", (string)null);
                });

            modelBuilder.Entity("GameServer.Docker.Data.V2.GameTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("CurrentRevisionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentationUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("GameTypes", (string)null);
                });

            modelBuilder.Entity("GameServer.Docker.Data.V2.GameTypePortEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AdvertisedPort")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContainerPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameTypeRevisionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameTypeRevisionId");

                    b.HasIndex("GameTypeRevisionId", "AdvertisedPort");

                    b.ToTable("GameTypePorts", null, t =>
                        {
                            t.HasCheckConstraint("CK_GameTypePorts_Protocol", "Protocol IN ('tcp', 'udp')");

                            t.HasCheckConstraint("CK_GameTypePorts_Range", "ContainerPort >= 1 AND ContainerPort <= 65535");
                        });
                });

            modelBuilder.Entity("GameServer.Docker.Data.V2.GameTypeRevisionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("EnableTTY")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageDigest")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageReference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("VersionTag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameTypeId", "ImageReference", "VersionTag")
                        .IsUnique();

                    b.ToTable("GameTypeRevisions", (string)null);
                });

            modelBuilder.Entity("GameServer.Docker.Data.V2.GameTypeSettingDefinitionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameTypeRevisionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameTypeRevisionId", "SettingKey")
                        .IsUnique();

                    b.ToTable("GameTypeSettingDefinitions", (string)null);
                });

            modelBuilder.Entity("GameServer.Docker.Data.V2.GameTypeSettingMetadataEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowedValuesJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoAllocatePort")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CannotBeEmpty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DataType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("GameTypeSettingDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Placeholder")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ValidateRelatedPortsAvailability")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValidationMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidationPattern")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueMappingsJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameTypeSettingDefinitionId")
                        .IsUnique();

                    b.ToTable("GameTypeSettingMetadata", (string)null);
                });

            modelBuilder.Entity("GameServer.Docker.Data.V2.GameTypeSettingPortMappingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CalculationValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameTypeSettingMetadataId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MappingRole")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RelationType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetContainerPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetProtocol")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("udp");

                    b.HasKey("Id");

                    b.HasIndex("GameTypeSettingMetadataId");

                    b.ToTable("GameTypeSettingPortMappings", null, t =>
                        {
                            t.HasCheckConstraint("CK_GameTypeSettingPortMappings_Protocol", "TargetProtocol IN ('tcp', 'udp')");

                            t.HasCheckConstraint("CK_GameTypeSettingPortMappings_Role", "MappingRole IN (0, 1)");

                            t.HasCheckConstraint("CK_GameTypeSettingPortMappings_Type", "RelationType IN (0, 1, 2, 3)");
                        });
                });

            modelBuilder.Entity("GameServer.Docker.Data.V2.GameTypeVolumeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnsureNfsPathExists")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameTypeRevisionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MountType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OwnerGid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerGidVariable")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OwnerUid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerUidVariable")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Permissions")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ReadOnly")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Required")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Usage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameTypeRevisionId");

                    b.HasIndex("MountType");

                    b.ToTable("GameTypeVolumes", (string)null);
                });

            modelBuilder.Entity("GameServer.Docker.Data.V2.GameTypeWebHostEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContainerPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContainerPortVariable")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnabledWhen")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("GameTypeRevisionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PathSegment")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameTypeRevisionId");

                    b.ToTable("GameTypeWebHosts", (string)null);
                });

            modelBuilder.Entity("GameServer.Docker.Data.V2.MountTypeConfigEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("VolumeNameFormat")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("MountTypeConfigs", (string)null);

                    b.HasData(
                        new
                        {
                            Key = "volume",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Docker volume",
                            IsActive = true,
                            OptionsJson = "{\"Driver\":\"local\",\"SourcePathTemplate\":\"{gameTypeKey}_{serverId}_{Source}\",\"DefaultReadOnly\":\"false\",\"DefaultEnsureNfsPathExists\":\"false\"}",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            VolumeNameFormat = "{gameTypeKey}_{serverId}_{Source}"
                        },
                        new
                        {
                            Key = "nfs",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "NFS volume",
                            IsActive = true,
                            OptionsJson = "{\"Driver\":\"local\",\"DriverOptionsJson\":\"{\\\"type\\\":\\\"nfs\\\",\\\"device\\\":\\\":/exported/path\\\",\\\"o\\\":\\\"addr=host.docker.internal,rw\\\"}\",\"SourcePathTemplate\":\"{gameTypeKey}_{serverId}_{Source}\",\"DefaultReadOnly\":\"false\",\"DefaultEnsureNfsPathExists\":\"true\"}",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            VolumeNameFormat = "{gameTypeKey}_{serverId}_{Source}"
                        });
                });

            modelBuilder.Entity("GameServer.Docker.Data.V2.GameServerEntity", b =>
                {
                    b.HasOne("GameServer.Docker.Data.V2.GameTypeRevisionEntity", "GameTypeRevision")
                        .WithMany("Servers")
                        .HasForeignKey("GameTypeRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameTypeRevision");
                });

            modelBuilder.Entity("GameServer.Docker.Data.V2.GameServerSettingEntity", b =>
                {
                    b.HasOne("GameServer.Docker.Data.V2.GameServerEntity", "GameServer")
                        .WithMany("Settings")
                        .HasForeignKey("GameServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameServer");
                });

            modelBuilder.Entity("GameServer.Docker.Data.V2.GameServerVolumeEntity", b =>
                {
                    b.HasOne("GameServer.Docker.Data.V2.GameServerEntity", "GameServer")
                        .WithMany("Volumes")
                        .HasForeignKey("GameServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameServer");
                });

            modelBuilder.Entity("GameServer.Docker.Data.V2.GameTypePortEntity", b =>
                {
                    b.HasOne("GameServer.Docker.Data.V2.GameTypeRevisionEntity", "GameTypeRevision")
                        .WithMany("Ports")
                        .HasForeignKey("GameTypeRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameTypeRevision");
                });

            modelBuilder.Entity("GameServer.Docker.Data.V2.GameTypeRevisionEntity", b =>
                {
                    b.HasOne("GameServer.Docker.Data.V2.GameTypeEntity", "GameType")
                        .WithMany("Revisions")
                        .HasForeignKey("GameTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameType");
                });

            modelBuilder.Entity("GameServer.Docker.Data.V2.GameTypeSettingDefinitionEntity", b =>
                {
                    b.HasOne("GameServer.Docker.Data.V2.GameTypeRevisionEntity", "GameTypeRevision")
                        .WithMany("SettingDefinitions")
                        .HasForeignKey("GameTypeRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameTypeRevision");
                });

            modelBuilder.Entity("GameServer.Docker.Data.V2.GameTypeSettingMetadataEntity", b =>
                {
                    b.HasOne("GameServer.Docker.Data.V2.GameTypeSettingDefinitionEntity", "GameTypeSettingDefinition")
                        .WithOne("Metadata")
                        .HasForeignKey("GameServer.Docker.Data.V2.GameTypeSettingMetadataEntity", "GameTypeSettingDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameTypeSettingDefinition");
                });

            modelBuilder.Entity("GameServer.Docker.Data.V2.GameTypeSettingPortMappingEntity", b =>
                {
                    b.HasOne("GameServer.Docker.Data.V2.GameTypeSettingMetadataEntity", "GameTypeSettingMetadata")
                        .WithMany("PortMappings")
                        .HasForeignKey("GameTypeSettingMetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameTypeSettingMetadata");
                });

            modelBuilder.Entity("GameServer.Docker.Data.V2.GameTypeVolumeEntity", b =>
                {
                    b.HasOne("GameServer.Docker.Data.V2.GameTypeRevisionEntity", "GameTypeRevision")
                        .WithMany("Volumes")
                        .HasForeignKey("GameTypeRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameServer.Docker.Data.V2.MountTypeConfigEntity", null)
                        .WithMany()
                        .HasForeignKey("MountType")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_GameTypeVolumes_MountTypeConfigs_MountType");

                    b.Navigation("GameTypeRevision");
                });

            modelBuilder.Entity("GameServer.Docker.Data.V2.GameTypeWebHostEntity", b =>
                {
                    b.HasOne("GameServer.Docker.Data.V2.GameTypeRevisionEntity", "GameTypeRevision")
                        .WithMany("WebHosts")
                        .HasForeignKey("GameTypeRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameTypeRevision");
                });

            modelBuilder.Entity("GameServer.Docker.Data.V2.GameServerEntity", b =>
                {
                    b.Navigation("Settings");

                    b.Navigation("Volumes");
                });

            modelBuilder.Entity("GameServer.Docker.Data.V2.GameTypeEntity", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("GameServer.Docker.Data.V2.GameTypeRevisionEntity", b =>
                {
                    b.Navigation("Ports");

                    b.Navigation("Servers");

                    b.Navigation("SettingDefinitions");

                    b.Navigation("Volumes");

                    b.Navigation("WebHosts");
                });

            modelBuilder.Entity("GameServer.Docker.Data.V2.GameTypeSettingDefinitionEntity", b =>
                {
                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("GameServer.Docker.Data.V2.GameTypeSettingMetadataEntity", b =>
                {
                    b.Navigation("PortMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
