// <auto-generated />
using System;
using GameServer.Docker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameServer.Docker.Data.Migrations
{
    [DbContext(typeof(GameServerDbContext))]
    [Migration("20260305055844_RemoveCheckConstraintFromModel")]
    partial class RemoveCheckConstraintFromModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("GameServer.Docker.Data.DefaultSettingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingValue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SettingKey");

                    b.HasIndex("GameTypeId", "SettingKey")
                        .IsUnique();

                    b.ToTable("DefaultSettings", (string)null);
                });

            modelBuilder.Entity("GameServer.Docker.Data.ExtendedMetadataEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CustomPropertiesJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableTTY")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("GameTypeId")
                        .IsUnique();

                    b.ToTable("ExtendedMetadata", (string)null);
                });

            modelBuilder.Entity("GameServer.Docker.Data.GameTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentationUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("GameTypes", (string)null);
                });

            modelBuilder.Entity("GameServer.Docker.Data.PortEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefaultPort")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameTypeId");

                    b.HasIndex("IsDefaultPort");

                    b.ToTable("Ports", null, t =>
                        {
                            t.HasCheckConstraint("CK_Ports_Protocol", "Protocol IN ('tcp', 'udp')");

                            t.HasCheckConstraint("CK_Ports_Range", "Port >= 1 AND Port <= 65535");
                        });
                });

            modelBuilder.Entity("GameServer.Docker.Data.PortRelationshipEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FixedValue")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("OffsetValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RelationType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SettingMetadataId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetContainerPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetProtocol")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("udp");

                    b.HasKey("Id");

                    b.HasIndex("SettingMetadataId");

                    b.ToTable("PortRelationships", null, t =>
                        {
                            t.HasCheckConstraint("CK_PortRelationships_Protocol", "TargetProtocol IN ('tcp', 'udp')");

                            t.HasCheckConstraint("CK_PortRelationships_Type", "RelationType IN (0, 1, 2)");
                        });
                });

            modelBuilder.Entity("GameServer.Docker.Data.PortValidationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CheckAvailability")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsUserEditable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("MaxPort")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(65535);

                    b.Property<int>("MinPort")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1024);

                    b.Property<string>("ReservedPortsJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("SettingMetadataId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SuggestedPortsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidationMessage")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SettingMetadataId")
                        .IsUnique();

                    b.ToTable("PortValidation", null, t =>
                        {
                            t.HasCheckConstraint("CK_PortValidation_Range", "MinPort >= 1 AND MinPort <= MaxPort AND MaxPort <= 65535");
                        });
                });

            modelBuilder.Entity("GameServer.Docker.Data.SettingMetadataEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowedValuesJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoAllocatePort")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CannotBeEmpty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DataType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultSettingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LinkedContainerPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ListDelimiter")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(",");

                    b.Property<bool>("MapsToContainerPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Placeholder")
                        .HasColumnType("TEXT");

                    b.Property<string>("PortProtocol")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("tcp");

                    b.Property<string>("SynchronizedWithSetting")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ValidateRelatedPortsAvailability")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("ValidationMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidationPattern")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueMappingsJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("DefaultSettingId")
                        .IsUnique();

                    b.HasIndex("MapsToContainerPort");

                    b.ToTable("SettingsMetadata", (string)null);
                });

            modelBuilder.Entity("GameServer.Docker.Data.VolumeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReadOnly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameTypeId");

                    b.ToTable("Volumes", (string)null);
                });

            modelBuilder.Entity("GameServer.Docker.Data.DefaultSettingEntity", b =>
                {
                    b.HasOne("GameServer.Docker.Data.GameTypeEntity", "GameType")
                        .WithMany("DefaultSettings")
                        .HasForeignKey("GameTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameType");
                });

            modelBuilder.Entity("GameServer.Docker.Data.ExtendedMetadataEntity", b =>
                {
                    b.HasOne("GameServer.Docker.Data.GameTypeEntity", "GameType")
                        .WithOne("ExtendedMetadata")
                        .HasForeignKey("GameServer.Docker.Data.ExtendedMetadataEntity", "GameTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameType");
                });

            modelBuilder.Entity("GameServer.Docker.Data.PortEntity", b =>
                {
                    b.HasOne("GameServer.Docker.Data.GameTypeEntity", "GameType")
                        .WithMany("Ports")
                        .HasForeignKey("GameTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameType");
                });

            modelBuilder.Entity("GameServer.Docker.Data.PortRelationshipEntity", b =>
                {
                    b.HasOne("GameServer.Docker.Data.SettingMetadataEntity", "SettingMetadata")
                        .WithMany("PortRelationships")
                        .HasForeignKey("SettingMetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SettingMetadata");
                });

            modelBuilder.Entity("GameServer.Docker.Data.PortValidationEntity", b =>
                {
                    b.HasOne("GameServer.Docker.Data.SettingMetadataEntity", "SettingMetadata")
                        .WithOne("PortValidation")
                        .HasForeignKey("GameServer.Docker.Data.PortValidationEntity", "SettingMetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SettingMetadata");
                });

            modelBuilder.Entity("GameServer.Docker.Data.SettingMetadataEntity", b =>
                {
                    b.HasOne("GameServer.Docker.Data.DefaultSettingEntity", "DefaultSetting")
                        .WithOne("SettingsMetadata")
                        .HasForeignKey("GameServer.Docker.Data.SettingMetadataEntity", "DefaultSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefaultSetting");
                });

            modelBuilder.Entity("GameServer.Docker.Data.VolumeEntity", b =>
                {
                    b.HasOne("GameServer.Docker.Data.GameTypeEntity", "GameType")
                        .WithMany("Volumes")
                        .HasForeignKey("GameTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameType");
                });

            modelBuilder.Entity("GameServer.Docker.Data.DefaultSettingEntity", b =>
                {
                    b.Navigation("SettingsMetadata");
                });

            modelBuilder.Entity("GameServer.Docker.Data.GameTypeEntity", b =>
                {
                    b.Navigation("DefaultSettings");

                    b.Navigation("ExtendedMetadata");

                    b.Navigation("Ports");

                    b.Navigation("Volumes");
                });

            modelBuilder.Entity("GameServer.Docker.Data.SettingMetadataEntity", b =>
                {
                    b.Navigation("PortRelationships");

                    b.Navigation("PortValidation");
                });
#pragma warning restore 612, 618
        }
    }
}
